name: env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - torchvision=0.10.0=py38_cu111
  - cudatoolkit=11.1.74=h6bb024c_0
  - pip:
    - matplotlib==3.4.3
    - pandas==1.3.4
    - scikit-image==0.18.3
    - h5py==3.1.0
    - scipy==1.7.1
    - seaborn==0.11.2
    - numpy==1.21.4
    - pycocotools==2.0.4
    - opencv-contrib-python==4.1.2.30
    - opencv-python==4.1.2.30
    - jupyterlab==3.3.0
